pr:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.12"
      addToPath: true
    displayName: "Use Python 3.12"
  - template: Test.yaml
  - template: Build.yaml