trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "v*"

pool:
  vmImage: ubuntu-latest

jobs:
  - template: TestTmpl.yaml
  - template: BuildTmpl.yaml
  - template: PublishTmpl.yaml