trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "v*"

pool:
  vmImage: ubuntu-latest

jobs:
  - template: CICD-pipelines/TestTmpl.yaml
  - template: CICD-pipelines/BuildTmpl.yaml
  - template: CICD-pipelines/PublishTmpl.yaml