parameters:
  - name: PythonBuildVersion
    type: string
    default: "3.12"

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "v*"

pool:
  vmImage: ubuntu-latest

jobs:
  - template: CICD-pipelines/TestTmpl.yaml
    parameters:
      PythonBuildVersion: ${{ parameters.PythonBuildVersion }}
  - template: CICD-pipelines/BuildTmpl.yaml
    parameters:
      PythonBuildVersion: ${{ parameters.PythonBuildVersion }}
  - template: CICD-pipelines/PublishTmpl.yaml
    parameters:
      PythonBuildVersion: ${{ parameters.PythonBuildVersion }}