pr:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

jobs:
  - template: CICD-pipelines/TestTmpl.yaml
    parameters:
      PythonBuildVersion: "{{ cookiecutter.parameters }}"
  - template: CICD-pipelines/BuildTmpl.yaml
    parameters:
      PythonBuildVersion: "{{ cookiecutter.parameters }}"