name: "Install-dependencies-and-{{cookiecutter.package_name}}"
description: "Install {{cookiecutter.package_name}} and its dependencies"
runs:
  using: "composite"
  steps:
    - name: Install-dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[test, docs]
      shell: bash
