name: "Install-dependencies-and-{{cookiecutter.package_name}}"
description: "Install {{cookiecutter.package_name}} and its dependencies"
runs:
  using: "composite"
  steps:
    - name: Install-dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        pip install -r docs_requirements.txt
        pip install -e .
      shell: bash
