name: build docs

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  merge_group:
    branches: ['main']

jobs:
  builddocs:

    runs-on: {{cookiecutter.a_start}}{ matrix.os }{{cookiecutter.a_end}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        exclude:
          - os: windows-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.10
    env:
      OS: {{cookiecutter.a_start}}{ matrix.os }{{cookiecutter.a_end}}
      UPLOAD_TO_GHPAGES: {{cookiecutter.a_start}}{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && github.event_name == 'push' && github.ref == 'refs/heads/master' }{{cookiecutter.a_end}}
      # we expect no warnings from Sphinx in 3.10
      # The std-lib docstring of IntEnum in 3.11.0 is not valid
      # causing errors like in the docstring of from_bytes (from Int)
      # WARNING: Inline interpreted text or phrase reference start-string without end-string.
      SPHINX_WARNINGS_AS_ERROR: {{cookiecutter.a_start}}{ matrix.python-version == '3.10' }{{cookiecutter.a_end}}
      SPHINX_OPTS: "-v"
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        # we need full history with tags for the version number
        fetch-depth: '0'
    - name: set-sphinx-opts
      run: |
        echo "SPHINX_OPTS=-W -v" >> $GITHUB_ENV
      if: {{cookiecutter.a_start}}{ fromJSON(env.SPHINX_WARNINGS_AS_ERROR) }{{cookiecutter.a_end}}
    - name: install pandoc linux
      run: |
        sudo apt update
        sudo apt install pandoc
      if: runner.os == 'Linux'
    - name: Install pandoc on windows
      uses: Wandalen/wretry.action@v1.3.0
      with:
        action: crazy-max/ghaction-chocolatey@v1.6.0
        with: |
          args: install pandoc
        attempt_limit: 5
        attempt_delay: 1000
      if: runner.os == 'Windows'
    - name: Set up Python {{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}
      uses: actions/setup-python@v4.3.1
      with:
        python-version: {{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          requirements.txt
    - name: upgrade pip setuptools wheel
      run: python -m pip install --upgrade pip setuptools wheel
      shell: bash
    - name: install {{cookiecutter.package_name}}
      run: pip install -e .[ci]
    - name: Build docs on linux
      run: |
        cd docs
        export SPHINXOPTS="{{cookiecutter.a_start}}{ env.SPHINX_OPTS }{{cookiecutter.a_end}}"
        make html
      if: runner.os == 'Linux'
    - name: Build docs on windows
      run: |
        cd docs
        $env:SPHINXOPTS = "{{cookiecutter.a_start}}{ env.SPHINX_OPTS }{{cookiecutter.a_end}}"
        ./make.bat html
      if: runner.os == 'Windows'
    - name: Upload build docs
      uses: actions/upload-artifact@v3.1.2
      with:
        name: docs_{{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}_{{cookiecutter.a_start}}{ matrix.os }{{cookiecutter.a_end}}
        path: {{cookiecutter.a_start}}{ github.workspace }{{cookiecutter.a_end}}/docs/_build/html
    - name: Deploy to gh pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: {{cookiecutter.a_start}}{ github.workspace }{{cookiecutter.a_end}}/docs/_build/html
        clean: true
        single-commit: true
        git-config-email: "bot"
        git-config-name: "Documentation Bot"
      if: {{cookiecutter.a_start}}{ fromJSON(env.UPLOAD_TO_GHPAGES) }{{cookiecutter.a_end}}
