name: Run mypy and pytest


on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  merge_group:
    branches: ['master']

jobs:
  pytestmypy:

    runs-on: {{cookiecutter.a_start}}{ matrix.os }{{cookiecutter.a_end}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"] # ["3.10", "3.11", "3.12"]
        exclude:
          - os: windows-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.11"
    env:
      OS: {{cookiecutter.a_start}}{ matrix.os }{{cookiecutter.a_end}}
      PYTHON: {{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}

    steps:
    - uses: actions/checkout@v3.5.3
      with:
        submodules: true
        # we need full history with tags for the version number
        fetch-depth: '0'
    - name: Set up Python {{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}
      uses: actions/setup-python@v4.3.1
      with:
        python-version: {{cookiecutter.a_start}}{ matrix.python-version }{{cookiecutter.a_end}}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
    - name: upgrade pip setuptools wheel
      run: python -m pip install --upgrade pip setuptools wheel
      shell: bash
    - name: install {{cookiecutter.package_name}}
      run: |
        pip install .[ci]
    #- uses: jakebailey/pyright-action@v1.6.0
    #  with:
    #    version: 1.1.318
    - name: Run Mypy
      run: mypy -p {{cookiecutter.package_name}}
    - name: Test with pytest
      run: |
        pytest ./{{cookiecutter.package_name}}/tests/
